name: UITest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: malinskiy/action-android/install-sdk@release/0.1.2

      - run: sdkmanager platform-tools

      - run: adb devices

      - run: echo $ANDROID_HOME
          
      - name: Install NUnit.ConsoleRunner
        run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .
        
      - name: Run UnitTests
        run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe Hardware.dll
